### ISSUE TITLE
Do consistent handling of symbolic links

### ISSUE THREAD

**Issue by evgmik** [sahib/brig#101]
When we do recursive staging, symbolic links to a file just get dropped/unprocessed without warning to a user.

How to observe the problem:
From within `brig` repo do
```
ali stage docs/talk/images` 
ali ls /images
```
 and observe that there is no file `logo.png` in the `brig` file system.

If you stage the symlink explicitly, it get resolved to its target and staged:
`ali stage docs/talk/images/logo.png` stages the content of the link.
So we should do similar for the recursive staging: stage the content of the target.

On top of the bug report, here is 
Feature request: add symbolic or even hard linking capabilities to `brig`

**Comment by sahib** [comment]
> If you stage the symlink explicitly, it get resolved to its target and staged:
ali stage docs/talk/images/logo.png stages the content of the link.
So we should do similar for the recursive staging: stage the content of the target.

Agreed, should be a small fix in ``cmd/fs_handlers.go``. Doesn't affect the brig daemon, because he has no clue about symbolic links after all. I wonder if we should follow symbolic links by default or ignore them (with a warning). The issue is that symbolic links might build up cycles and we must be careful not to end in an endless loop.

>  Feature request: add symbolic or even hard linking capabilities to brig

No. Symbolic links make file system handling so much more complicated. They transform a tree of files into a graph, with cycles and dangling pointers. We should support them when working with input directories on filesystem that support them, but there should not be a file type "symlink" in brig itself. 

Hardlinks don't make much sense as a concept either for brig. It's the same data that is available in different paths, with the nice property that the data is stored only once. Internally we kinda support this by having file nodes that point to the same hash, but without the inconvenient other property of hardlinks: When editing one on a linux fs, you modify all other hardlinks. 

brig works like a reflink (which e.g. btrfs supports) where editing one file creates a new revision of the file, but does not the other.   We should support something like ``brig cp`` that creates such reflinks, as discussed in #63.

**Comment by evgmik** [comment]
> > If you stage the symlink explicitly, it get resolved to its target and staged:
> > ali stage docs/talk/images/logo.png stages the content of the link.
> > So we should do similar for the recursive staging: stage the content of the target.
> 
> Agreed, should be a small fix in `cmd/fs_handlers.go`. Doesn't affect the brig daemon, because he has no clue about symbolic links after all. I wonder if we should follow symbolic links by default or ignore them (with a warning). The issue is that symbolic links might build up cycles and we must be careful not to end in an endless loop.

I think we should follow symlinks to the end, even if it the loop and `brig` hangs. I know the endless loop might exist, but I have not seen one in real life. But this way we avoid  keeping a recursion/depth counter.

I will look into a fix to do this.

> > Feature request: add symbolic or even hard linking capabilities to brig
> 
> No. Symbolic links make file system handling so much more complicated. They transform a tree of files into a graph, with cycles and dangling pointers. We should support them when working with input directories on filesystem that support them, but there should not be a file type "symlink" in brig itself.

I hear you. Extra complication with a questionable benefit.
