### ISSUE TITLE
Google drive

### ISSUE THREAD

**Issue by gedw99** [sahib/brig#19]
This would be an awesome alternative to Google drive !

Looking at the gateway it looks pretty easy to add a webgui.

Is this something you are open to having added ?
Any impediments you can see ?

There is a fantastic file manager GUI for the caddy server that could be adapted to work with brig. It's pretty nice too.

**Comment by sahib** [comment]
Hey @gedw99,

> Looking at the gateway it looks pretty easy to add a webgui.

I assume you want some sort of "file browser" served to your browser?
That's quite possible and might be implemented in the future - the question is rather what priority that has, since there are quite a lot of more urgent areas to fix. I might look into caddy's implementation for that though. It's just a big topic that could be extended in every possible direction. :smirk:

> There is a fantastic file manager GUI for the caddy server that could be adapted to work with brig. It's pretty nice too.

I never tried that, but you might use that already by using the FUSE filesystem of brig and letting caddy serve that. Performance might not be perfect though.

**Comment by gedw99** [comment]
Nah too many layers.
The file manager web GUI is able to run as a SPA independent of caddy anyway 

Google it it's very nice and mature

**Comment by sahib** [comment]
I had some fun since new year's eve and implemented a prototype of a web UI with [Elm](https://elm-lang.org/):

![screenshot](https://brig.readthedocs.io/en/develop/_images/gateway.png)

I realized, some "visual bling bling" might help people get into brig and lure them to try it at least. Only the *Files* tab is currently working, others will be added over time. I have a demo of it running in a docker container [here](https://nwzmlh4iouqikobq.myfritz.net:5000) (no guarantee it will run all the time and I will remove the link once it is shut down).

**Comment by gedw99** [comment]
nice one @sahib 

ELM is functional. Was it pleasant to work with ?

**Comment by sahib** [comment]
> ELM is functional. Was it pleasant to work with ?

Very pleasant. Especially in direct comparison with JavaScript I wholeheartedly recommend it.
Even if I'd never use it again, it was an interesting learning experience. Had some bigger refactorings during development and it kept just working all the time, as long as it compiled. Kind of magic.

**Comment by makeworld-the-better-one** [comment]
@sahib Tried out the gateway now, it looks amazing! It's what I've been looking for after all this time, a nice UI for IPFS filesharing. Thanks so much! Can this issue be closed, since the gateway works, it's out of develop, and all the tabs work, not just files like you said above?

**Comment by makeworld-the-better-one** [comment]
Also if I can hijack this issue for a moment, it would be nice if the file UI providing an option to pin or unpin content. Other than that it looks very full featured, thanks again!

**Comment by makeworld-the-better-one** [comment]
Also I would suggest adding this to the README, if I may. It would make brig look a lot more attractive to users who are a bit afraid of the commandline, and even those who aren't :smile:

**Comment by sahib** [comment]
@makeworld-the-better-one: Thank you! 

> Can this issue be closed, since the gateway works, it's out of develop, and all the tabs work, not just files like you said above?

It's still in development (although it is in ``master``), but I guess the original request was... answered.

> Also I would suggest adding this to the README, if I may. It would make brig look a lot more attractive to users who are a bit afraid of the commandline, and even those who aren't

Probably. Didn't do it yet, since the gateway is still not totally out of the oven. I wanted to add some more documentation. Would appreciate a Pull request that mentions the UI in a pleasing way in the README (and also maybe adds some documentation?).

**Comment by sahib** [comment]
Closing. Discussion can still continue here though.

**Comment by makeworld-the-better-one** [comment]
> Would appreciate a Pull request that mentions the UI in a pleasing way in the README (and also maybe adds some documentation?)

Sure! Beyond adding it to the README, what documentation are you thinking of specifically? The UI tends to explain itself a lot, which is a good thing.

**Comment by sahib** [comment]
I was thinking to have at least some screenshots of each tab in a separate documentation section. Less for documentation though more for letting people see how it looks. Since I have to add some right management (not every user should be allowed to see the remotes tab for example) this could be explained along the way there. But you're right, the README is more important right now.

> The UI tends to explain itself a lot, which is a good thing.

Glad to hear. After all, I'm not UI/UX guy. :smile:

**Comment by makeworld-the-better-one** [comment]
I will make a PR for that soon, likely today. Happy to help out!

**Comment by makeworld-the-better-one** [comment]
Made the PR: #25
