### ISSUE TITLE
Read-only folder sharing

### ISSUE THREAD

**Issue by makeworld-the-better-one** [sahib/brig#28]
**Is your feature request related to a problem? Please describe.**
I can't share folders or files with remotes without feeling okay with them being able to edit and change everything in the folder.

**Describe the solution you'd like**
It'd be nice to be able to share a folder to a remote as read/view only, with a command like `brig remote folder add bob /videos --readonly`.

**Additional context**
This is basically a one-way sync, where `brig` wouldn't allow the user to edit the file, and if they did somehow, the other remote would reject their edit, and it would be overwritten with the next update.

**Comment by sahib** [comment]
Sounds to me a like a sensible feature request.

If you have no folders you could of course also choose to never sync with that remote, but I see that's only a partial solution. Shouldn't be too hard to implement. All remotes still may do a full fetch on your data, but a sync would ignore the fetched folder.

> This is basically a one-way sync, where `brig` wouldn't allow the user to edit the file, and if they did somehow, the other remote would reject their edit, and it would be overwritten with the next update.

I can't quite forbid others to change the data they got from you. After all, that's a decentralized application. The ``--readonly`` part would kick only in when syncing again with those peers  - causing the whole folder to be excluded from sync.

**Comment by makeworld-the-better-one** [comment]
> If you have no folders you could of course also choose to never sync with that remote, but I see that's only a partial solution. Shouldn't be too hard to implement. All remotes still may do a full fetch on your data, but a sync would ignore the fetched folder.

I'm confused what you are saying here. That instead of sharing a folder and allowing them to edit, I could just not share? I'm glad you think it's a good feature though.

> I can't quite forbid others to change the data they got from you. After all, that's a decentralized application.

I understand that, with FUSE and all. I was thinking you could warn the user when they try and do editing operations such as `edit` or `mv` or `cp`, etc, telling them that these changes won't sync.

> causing the whole folder to be excluded from sync.

I was actually thinking that it could cause the folder to be overwritten, what do you think of that? Is that a good idea? Because it's supposed to be readonly anyway, and you wouldn't want a mistaken edit to mean the folder never syncs again. Maybe it should be some sort of option?

**Comment by sahib** [comment]
That's now how it works. ``brig`` is like ``git`` here: It maintains a separate copy of all metadata for every remote. When you sync with somebody, you fetch the most up-to-date version of theirs (maybe with folders filtered they do not want you to see) and update your local copy with that. The actual "sync" is only a local operation then. ``brig sync`` is never bi-directional, i.e. it only ever changes stuff on your side. That hopefully explains my first comment: If you never want the changes from a specific remote (thus being "read only") you can simply choose to not call ``brig sync`` on them. Once it comes to individual folders though, it's not possible yet.

> I understand that, with FUSE and all. I was thinking you could warn the user when they try and do editing operations such as `edit` or `mv` or `cp`, etc, telling them that these changes won't sync.

FUSE is not responsible here (for a change). Since everyone has their own copy of the metadata, they're free to do whatever they please to. Imagine we have a remote ``bob`` and he syncs with us. We have one read-only folder ``/videos``. He will update his local copy of our metadata and sync with it, resulting in a ``/videos`` folder in his metadata. He is free to modify that in any way without a warning  - but when we sync with ``bob`` again we want to make sure that we don't get the changes in his ``/videos`` folder. We can do this by simply ignoring all "read only" folders during a sync.

> I was actually thinking that it could cause the folder to be overwritten, what do you think of that? Is that a good idea? Because it's supposed to be readonly anyway, and you wouldn't want a mistaken edit to mean the folder never syncs again. Maybe it should be some sort of option?

I'm not sure if I got that. You mean (with the example above in mind) if ``bob`` changes ``/videos`` but syncs again with us, his changes are overwritten? What for?

**Comment by makeworld-the-better-one** [comment]
That makes sense to me, I think.
As for `bob` editing, I was actually thinking, that when `bob` gets that folder shared, he can also see that it's been shared as readonly, it's part of the share message or whatever. So he (and `brig`) knows not to edit anything in it. `brig` would warn him about commands like I mentioned above, but if the edits happen anyway, it would be overwritten with next sync.

This makes the readonly idea more than just on the original node's side, it's something both that node and `bob` have to accept. It's a different model than what you were thinking, but I think it might be better, because it makes all nodes more aware of how things are, like how on Google Drive or something you know whether you are an editor or a reader.

**Comment by sahib** [comment]
> So he (and brig) knows not to edit anything in it.

That would only make sense in a centralized approach (or if you build something like that with ``brig``), where one repo (in the example above our repo) is a "blessed repo" that everyone trusts to have a sensible state. With ``brig`` however, ``bob`` could also modify ``/videos`` and share his edits with ``charlie`` (which does not have any read-only restrictions). 

Maybe better explained in ``git terms``: ``--read-only`` would only mean that you cannot ``git push``¹ to those folders. You can ``git pull`` as much as you want though, modify what you got and share it with other people. ``git`` wouldn't warn you about that either and I think that's perfectly right to do so (despite being tricky to implement).

¹: There is no ``brig push`` of course. Think of a "brig sync on our side" for now.  That might be another feature idea though, where ``brig push bob`` is a request for bob to sync with us (which he might decline).

> [...] but if the edits happen anyway, it would be overwritten with next sync.

I think that's a separate idea. For me that's a special way to resolve conflicts. If both parties have the same file, then the current solution is to either ignore (keep our side) or create a conflict file. A third option could be added (take the remote version) which could be configured on a per-remote base.

> [...] but I think it might be better, because it makes all nodes more aware of how things are [...]

Since every node decides for itself "how things are", I don't know if this makes sense. :smirk:

> [...] how on Google Drive or something you know whether you are an editor or a reader.

This is indeed a different model. Also one, that is harder to explain and understand in my opinion.
This would require ``brig`` to tell other nodes when it changed its remotes/folders (or the settings of it).

**Comment by makeworld-the-better-one** [comment]
Hmm, that makes more sense I guess. I suppose I'm thinking about the shared archive idea I mentioned before. There wouldn't be a "blessed repo", but I guess I was thinking there could be a shared accepted state, where someone could make a folder like `/archive`, share it with everyone, and then each person would make their own subfolders where they would archive their own stuff, and that others couldn't change. But I see that `brig` doesn't work that, way, because there are many configurations of sharing. 

> A third option could be added (take the remote version) which could be configured on a per-remote base.

Doing that along with this readonly stuff would be appreciated, I think it would be helpful for the scenario I'm thinking about above.

**Comment by makeworld-the-better-one** [comment]
> This would require `brig` to tell other nodes when it changed its remotes/folders (or the settings of it).

Continuing in this vein, Maybe something like `brig show /videos` will show what remotes this folder is shared with, and whether it's read-only or not. If it's read-only, it should also show who shared it with who (is this node sharing it, or was it shared with this node?), and whether this node has set the folder to be overridden with each update or not.

**Comment by sahib** [comment]
> Continuing in this vein, Maybe something like brig show /videos will show what remotes this folder is shared with, and whether it's read-only or not. 

That's not quite easy to implement, especially if you want this kind of information always up-to-date.
Surely a good though for later versions, but definitely not something I would focus on right now.

> If it's read-only, it should also show who shared it with who (is this node sharing it, or was it shared with this node?), and whether this node has set the folder to be overridden with each update or not.

I have a feature planned (long term) where it would be possible to say that at least n-nodes have to provide a file before being able to unpin it (without warning at least). This would require a similar infra structure. But until then, the current state should be good enough.

So, current state: I implemented three smaller features:

- ``brig remote add bob /videos --read-only`` works now in the way I described above. Other remotes are still able to see the folder (and area also able to modify it on their side), but the changes will not be synced back to us. If you combine this with the next feature you should be close to what you wanted.
- New conflict strategy called ``embrace``. This will always take the remote's version on conflicts - which is nice for archival nodes. You can set it on a per remote basis with ``brig remote conflict-strategy embrace bob``. Or shorter: ``brig rmt cs embrace bob``.
- ``brig push bob``: Asks bob to sync with us. This requires ``bob`` to allow pushes from us via ``brig remote accept-push enable bob`` . Or shorter: ``brig rmt ap e bob``.

Together they should be a big improvement and solve 95% of you original feature request.

**Comment by makeworld-the-better-one** [comment]
> That's not quite easy to implement, especially if you want this kind of information always up-to-date.
Surely a good though for later versions, but definitely not something I would focus on right now.

Fair enough, just an idea. Seeing remotes for folders and files is a nice thing, but definitely not necessary or anything.

> I have a feature planned (long term) where it would be possible to say that at least n-nodes have to provide a file before being able to unpin it (without warning at least). This would require a similar infra structure.

I feel like the infra for that is different, because it requires keeping track of a swarm of nodes, while what I was thinking was one-way, this node and the remote. There might be multiple one-way connections, but it doesn't have to be a swarm. But it was just another idea, and the feature you mention above is much more useful, I'll be glad to see it someday!

> Together they should be a big improvement and solve 95% of you original feature request.

Yes, wow, thanks a lot! I will test these out, but yes it totally solves my feature request. 😍

**Comment by sahib** [comment]
Wrote tests, updated the [docs](https://brig.readthedocs.io/en/develop/tutorial/remotes.html#conflicts) and also made it possible to configure the conflict strategy and push-ability as well as read-only folders in the frontend. Will close this issue tomorrow if there's nothing open then.

> I feel like the infra for that is different, because it requires keeping track of a swarm of nodes, while what I was thinking was one-way, this node and the remote. There might be multiple one-way connections, but it doesn't have to be a swarm. But it was just another idea, and the feature you mention above is much more useful, I'll be glad to see it someday!

Well, yeah. I over complicated things a bit in my head.

**Comment by makeworld-the-better-one** [comment]
That's so awesome! Thanks, and especially for not forgetting the frontend. Looking at the docs, I have one more question. Is there a way to set the conflict resolution strategy depending on the folder? That would be helpful, as sometimes I might want to edit files with a remote in one folder, but `embrace` them for another folder.

**Comment by sahib** [comment]
> Is there a way to set the conflict resolution strategy depending on the folder?

Could be another feature request. Can you come up with a good use case to convince me it is needed?

**Comment by makeworld-the-better-one** [comment]
> Could be another feature request.

Will do, and we can discuss there. I'm going to close this issue, and I'll open a new one if I find any bugs with this. Thanks again!
