### ISSUE TITLE
Delete doesn't remove a folder from view

### ISSUE THREAD

**Issue by makeworld-the-better-one** [sahib/brig#34]
**Describe the bug**
When clicking the delete button in the gateway, the folder I deleted stayed visible, but was deleted in the backend.

**To Reproduce**
Try and delete a folder and see that it stays visible

**Expected behavior**
The folder goes away in the view.

**Additional context**
The folder disappears as expected when clicking the "Files" tab again or reloading. It was actually deleted.

**Comment by makeworld-the-better-one** [comment]
I'll add that adding a remote doesn't add it to the remote view without reloading the whole page.

**Comment by sahib** [comment]
Both work for me, but I'm aware that the update might not work after some time.

Some background: When changing something, the frontend does not update its view automatically (because that would be a lot of special code), but waits for an event coming from the backend over a websocket. This websocket seems to be easily closed when changing networks, network lags or suspending your computer. I'll try to see if I can make it re-connect easily.

**Comment by sahib** [comment]
This should work better with 3f2ec067. If the problem persists, please paste the content of the web console (F12) and describe the exact steps you did plus the time/event after which it happened.

**Comment by sahib** [comment]
Please re-open when the issue happens again.
