### ISSUE TITLE
mention existing AUR package for archlinux users

### ISSUE THREAD

**Issue by vasket** [sahib/brig#40]
hello sahib,

thanks for your nice project.

i've created an AUR package. feel free to mention it somewhere.

https://aur.archlinux.org/packages/brig-git

**Comment by sahib** [comment]
Hey @vasket,

thanks for the PKGBUILD! I mentioned it in the docs [as of this commit](https://github.com/sahib/brig/commit/944cb6e3cf5c8801bbb0fe3fcb3411463f2dc3cf#diff-548eb9ce4cac8e13a1238ad703272931R20).
It works as far as I can tell, but there are two smaller issues:

* Do not use ``go build``, use ``make``. Otherwise the version info will be missing.
* I get [one of those warnings](https://wiki.archlinux.org/index.php/makepkg#WARNING:_Package_contains_reference_to_$srcdir) during build.

Also, I wonder if it would be more useful if it builds from the ``develop`` branch, since the ``master`` branch contains the release versions anyways.

**Comment by vasket** [comment]
Hi @sahib,

you're welcome. 

* The `PKGBUILD` now uses `make` instead of `go build`
* Switched branch to `develop`
* The warning still exists, because I'm coping the compield binary into the package. I've no idea how to get around this, without braeking the build...

**Comment by sahib** [comment]
Cool, thanks.

> The warning still exists, because I'm coping the compiled binary into the package. I've no idea how to get around this, without breaking the build...

Right, the ``$srcdir`` reference is actually in the binary itself. Which is really not an issue. Let's ignore that issue then.

(Also, you might want to add ``make`` as build-dependency now.)

**Comment by sahib** [comment]
Hi @vasket,

sorry to bug you again, but I changed the build process slightly: The ``make`` step now becomes ``go run mage.go``. I wanted to do this before other people create packages fro ``brig``. See [this issue](https://github.com/sahib/brig/issues/26) for more details.

**Comment by vasket** [comment]
Greetings @sahib,

`go run mage.go` complaining about missing parcello binary:
```
gateway/static/package.go:3: running "parcello": exec: "parcello": executable file not found in $PATH
gateway/templates/package.go:3: running "parcello": exec: "parcello": executable file not found in $PATH
Error: running "go generate ./..." failed with exit code 1
exit status 1
```
I guess that https://github.com/phogolabs/parcello is missing.

If that is correct i'll package that for archlinux as well and try to build again.

**Comment by sahib** [comment]
No, that's just my bad. Please try again with the latest ``develop`` branch.
By the way, I guess you do not need to download the full git repository in your PKGBUILD since you only need the most recent commit. Maybe you can check [this](https://unix.stackexchange.com/questions/154919/how-to-modify-a-pkgbuild-which-uses-git-sources-to-pull-only-a-shallow-clone) to find out how to limit the ``--depth``.

**Comment by vasket** [comment]
updated PKGBUILD

compile and runs for me.

is it possible to to add a `make install `equivalent to the magefiel? this would make it possible to get rid of packageing warning.

**Comment by sahib** [comment]
> compile and runs for me.

I had an issue in ``install()``. It failed to copy the binary, because it was outputted somewhere else (probably because I have ``GOBIN`` set to something else). This fixed the binary destination:

```bash
GOBIN="${srcdir}/${_pkgname}" go run mage.go b
```

> is it possible to to add a make install equivalent to the magefiel? this would make it possible to get rid of packageing warning.

Since we can't really run the ``go`` binary as root, we can't really offer much as ``install`` target. It would be a ``sudo cp brig /usr/bin`` anyways.

**Comment by vasket** [comment]
fixed 
my `GOBIN `was empty so it worked for me.

Hm, if I've got time i'll try to fix that warnig.

**Comment by sahib** [comment]
Can confirm it works. :+1: 

> Hm, if I've got time i'll try to fix that warnig.

Don't worry, it's not too important from my point of view.

**Comment by vasket** [comment]
It isn't but it sitll bugging me :P
