### ISSUE TITLE
Why not Gitless

### ISSUE THREAD

**Issue by DonaldTsang** [sahib/brig#45]
**Describe the solution you'd like**
Usage of Gitless-like command for simplified usage https://github.com/sdg-mit/gitless

**Comment by sahib** [comment]
Hello @DonaldTsang,

can you please elaborate a bit more? The commands of ``brig`` are only loosely based on ``git`` and were simplified a bit already.

**Comment by DonaldTsang** [comment]
According to the website https://gitless.com/
> Gitless is a Git-compatible version control system, that is easy to learn and use:
> - Simple commit workflow
> - Independent branches
> - Friendly command-line interface
> - Compatible with Git
>
> Because Gitless is implemented on top of Git, you can always fall back on Git. And your coworkers you share a repo with need never know that you're not a Git aficionado. Moreover, you can use Gitless with GitHub or with any Git hosting service 

So it might be a good way to enhance Brig through the use of Gitless in order to enhance the user experience of developing software through IPFS.

**Comment by sahib** [comment]
Yes, but ``gitless`` is just a more convenient interface to ``git``. Since ``brig`` doesn't really use ``git`` (it just looks a bit like it), we have no relation to ``gitless``. Do you maybe mean that some workflow changes that ``gitless`` did could be also implemented for ``brig``? If so, could you point those out please and how they fit into brig's model?

**Comment by DonaldTsang** [comment]
The idea is that gitless is created by MIT as a UX modification of git and I think brig can get a face-lift with gitless techniques. A this notes a lot of git-like systems have similar problems https://spderosso.github.io/oopsla16.pdf

**Comment by sahib** [comment]
> The idea is that gitless is created by MIT as a UX modification of git and I think brig can get a face-lift with gitless techniques. 

Being created by the MIT doesn't make it a silver bullet sadly. The point of gitless is that it's a very specific improvement to problems of ``git`` as a case study for user interaction concepts. Transporting those concepts to other projects that do not do the same is hardly possible. 

> A this notes a lot of git-like systems have similar problems https://spderosso.github.io/oopsla16.pdf

I had a rough look at the misfit list presented in that paper and didn't find something that applies to brig or was not yet tackled. Please state specific improvements related to brig. Otherwise I will close this issue.
