### ISSUE TITLE
avoid creating of temporary files in StageFromReader of client/fs_cmds.go

### ISSUE THREAD

**Issue by evgmik** [sahib/brig#61]
The StageFromReader is used when brig is staging from stdin:
 `echo test | brig stage --stdin testfile`

Internally it creates a temporary file by copying the content of the stream (stdin)
and then uses a regular Stage command suitable for a file staging.  This is very space and probably time inefficient. Assume some one want to stage 1GB of data via piping to the brig. Then `brig` should copy it all to a file (time consuming), then read it back for staging (also takes time), on top of it we consumed 1GB of temporary storage.

There must be a way just to stage from the input stream directly.

**Comment by sahib** [comment]
Agreed, ``--stdin`` was just a quick feature that I just wanted to get work quickly  :smile: 

I see two ways:

* Either write file to a unix socket and pass path to the daemon. Then we would not buffer it all in memory, just memory for the internal read/write buffer of the socket is needed.
* Offer an Cap'n'Proto API called ``stageStream`` [to directly accept streams](https://github.com/sahib/brig/blob/3c880455d299a46e6110c5032b0c2d367225831c/server/capnp/local_api.capnp#L138) and not paths. 

Cleaner one is probably option 2. See here for some background:

* https://capnproto.org/news/2020-04-23-capnproto-0.8.html

Maybe a good task to get more familiar with the ``.capnp`` files.

------

Side note: Connection between server and client is currently a TCP connection. Maybe it's long term better to use a unix socket for [performance reasons](https://stackoverflow.com/questions/14973942/tcp-loopback-connection-vs-unix-domain-socket-performance#:~:text=Unix%20domain%20sockets%20are%20often,and%20servers%20on%20different%20hosts.). This becomes more relevant when we pipe complete files over the connection.

**Comment by evgmik** [comment]
I think new features of cpnproto are not yet implemented in go. I will look how brig's  `cat` is implemented, where we stream from server side to client, to see how to do `stage`.

I was trying to see it it possible with `fifo` files but hit a dead end. But it might be even faster than other alternatives.

**Comment by sahib** [comment]
> I think new features of cpnproto are not yet implemented in go. 

Hmm, yes. Seems like it, but we don't need the new features since streaming was possible very early on in Cap'n'p.
The first part of the link details on what is already available, the second half of the link just introduces the new ``stream`` keyword as syntactic sugar.

> I will look how brig's cat is implemented, where we stream from server side to client, to see how to do stage.

``brig cat`` is not exactly a good role model here. It boots up a small TCP server on a random port and delivers the port to the client. The client then pulls the file from the port. The reason I implemented it like this are rather simple:

* TCP sockets are very portable and I want ``brig`` to work also on other platforms, although linux is the main target for now.
* I didn't get at that time how streaming with cap'n'proto works and didn't bother to research. :smile: 

I'm sure ``brig cat`` could also be improved performance wise (we don't really need expensive TCP for localhost transfers).
This could be another ticket, albeit another low-prio one.

> I was trying to see it it possible with fifo files but hit a dead end. But it might be even faster than other alternatives.

FIFOs might work too and will be very fast, but are not very portable. What was the dead end you hit?


----

I guess it boils down to the question: Do we need the added speed? Is it worth to introduce platform specific for it? 
I'm fine with the following options:

* Implement the streaming in a portable way using Cap'n Proto.
* Postpone that feature to 0.7.0 and do some more research regarding speed. The original issue (extra temporary file) has been resolved.

Additionally (in both cases) we can do what the docker daemon does: Use unix domain socket for communication between control client and daemon on platforms that support it and TCP sockets elsewhere. This would also indirectly speed up the file transfer if we go for Cap'n Proto and could be considered a security feature since UDS make it harder to access the brig daemon over network which is not intended.

**Comment by evgmik** [comment]
I would like to speed up staging and reading for 0.6.0.

Here is a short benchmark.

# Reading speed

I created 500 MB file from /dev/urand to avoid compression at the brig backend and staged it into the brig.

## brig
Reading this file with `brig cat filename | pipemeter >/dev/null` gives me around 19 MB/S (with consequent runs, so all blocks are cached in memory).

## ipfs
Accessing the same file via backend hash directly with `ipfs cat hash | pipemeter >/dev/null` shows 42MB/S. I.e. 

ipfs delivers the file by factor of 2 faster.
We do have encryption overhead, but factor of 2 seems bad.

# Staging speed 500 MB file

## brig
`dd if=/dev/urandom count=1000k | ./brig stage --stdin trand2` takes about 40 seconds. Transfer  speed is 12.5 MB/S.

## ipfs
`dd if=/dev/urandom count=1000k | ipfs add` takes 24 seconds: Transfer speed is 21 MB/s

Note again about factor of 2 speed difference. But writing slow brig's transfer is
understandable, we have to write data twice: to the temporary file and to the backend storage. The rest of writing speed is limited by my spinning hard drive speed.

# Conclusion
Factor of 2 is something worth fighting *now*.

**Comment by evgmik** [comment]
My dead end with FIFO was lack of an example how to manage a stream from client to the backend. Looks like everywhere in a brig, client never sends big chunks of data. Whenever data is sent, we do it with by sending a filename where it is contained.

But fifo file or stream requires an active thread to push data into the stream, a pattern new for me. This is why I wanted to use `cat` where something like this is implemented.

**Comment by evgmik** [comment]
Ok. I am out of this rabbit hole :)

# reading speed
I tried Unix Domain sockets (UDS) versus TCP socket for the `brig cat`.

On my machine `brig cat random500MBfile | pipemeter > /dev/null' produces
- 18.52 MB/S with TCP socket
- 19.23 MB/S with UDS

I think 4% increase throughput is not worse the effort yet. The question remains
why `ipfs cat` is factor of **2** faster.

Is decryption that expensive? I am quite sure there were no compression due to randomness.

# staging limitations
During staging we need seekable stream: we read a part of the stream to check for the best compression algorithm, and then the whole stream to generate encryption key, then we read from 0 position again to commit to encrypted stream to IPFS.

Am I right about it?

If I am correct:
- we have to use a temporary file for staging from stdin, since we need to convert it to something seekable;
- we will have read twice penalty, though if file already sits in the memory
this should be very fast. Thus I blame the encryption overhead yet again.

Do we have any encryption throughput benchmarks?

**Comment by sahib** [comment]
> Factor of 2 is something worth fighting now.

I somewhat disagree.

For 0.6.0 I want to focus on correctness and stability and it doesn't matter how fast we're producing wrong results - and from my experience factor 2 is not even that big - considering we're talking about largely unoptimized pre-alpha software that also does more things than ipfs during staging. To be honest, I expected/remembered worse.

If you really want to do it, I won't reject a PR though. :smirk: But be warned, this will be a deep rabbit hole and I think it's better to get the functionality right first. Introducing optimizations early make things harder because you need to maintain the speed in future releases (by checking with automated regression tests) and often premature optimizations make changing the program harder. The original issue here was that ``brig stage --stdin`` creates a wasteful temporary file which be will be a problem for big files. Let's fix this first before jumping to ``brig cat`` (although this will need a slightly more fundamental change as you see later).

> Note again about factor of 2 speed difference. But writing slow brig's transfer is
> understandable, we have to write data twice: to the temporary file and to the backend storage. The rest of writing speed is limited by my spinning hard drive speed.

Yes, for the general benchmark you should probably not use ``--stdin`` since we know that it sucks.  As a general tip: Create your ipfs repo and all benchmark assets in /tmp (which usually is a memory backed tmpfs) to minimize the dependency on your slow hard drive.

> My dead end with FIFO was lack of an example how to manage a stream from client to the backend. Looks like everywhere in a brig, client never sends big chunks of data. Whenever data is sent, we do it with by sending a filename where it is contained.

Yes, that was the quick and dirty way I mentioned in my post before. It's wasteful but is probably not insanely slow since the file is created in ``/tmp``.

> But fifo file or stream requires an active thread to push data into the stream, a pattern new for me. This is why I wanted to use cat where something like this is implemented.

That's correct. One end needs to feed the queue (be it UDS or fifos or shared memory), the other needs to read from it. It's a classic example where reader and writer need to synchronize. Before they synchronized by letting them client finish writing and only then do the reading.

> I think 4% increase throughput is not worse the effort yet. The question remains
> why ipfs cat is factor of 2 faster.

This is a hint that the stream is not the limiting factor here. 4% is not worth it.

> We do have encryption overhead, but factor of 2 seems bad. [...]
> Is decryption that expensive? I am quite sure there were no compression due to randomness.

That depends a lot on your CPU, i.e. if it supports the ``aes`` IS. But possibly yes. The only way to find out is to properly benchmark the following stages of the pipe:

* Throughput of our internal ``ipfs cat`` and ``ipfs add`` implementations.
* Throughput of the compression/decompression layer.
* Throughput of the encryption/decryption layer.
* Throughput of TCP socket for the ``brig cat`` case.
* Throughput of File reading from /tmp for the ``brig stage`` case.
* Throughput of a simple copy from stdin to stdout (this is the I/O baseline your CPU can do - that's roughly 32 MB/s for my slow laptop).

Each of these steps build a chain, where every link slows down the system. It would be really cool if we would have [automated benchmarks](https://dave.cheney.net/2013/06/30/how-to-write-benchmarks-in-go) for this.

> During staging we need seekable stream: we read a part of the stream to check for the best compression algorithm, and then the whole stream to generate encryption key, then we read from 0 position again to commit to encrypted stream to IPFS.
>
> Am I right about it?

Yes, you are. The reason why we need a seekable stream (and I only remembered this now):

* We need the size of the stream. I build in a generic way that does not rely on files but on streams.
  Streams don't have a size and the only way to know is to either read all or seek to the end.
* The hash of the file is generated. This is used either as encryption key or to check if we need to do more work (if the content hash did not change, there's no need to stage the file).
* Part of the header is used to guess the compression algorithm we should use.

[See this function](https://github.com/sahib/brig/blob/9f2e5a94c163eb67e5acc74540a11ceeaaed8f9b/catfs/fs.go#L870).

We probably can live without the compression guessing. Getting rid of the hash is harder, then we need another encryption guessing mechanism.  Current scheme is: If a file was initially added, compute the content hash+size and derive the key from it. If the file is modified the existing key is taken over. The idea here was that we want to enable de-duplication for the same files (although this is partly defeated by how our block encryption works). If we would change the key on each modification the resulting cipher text would be completely different of course.

Another scheme could be that we just generate one encryption key per repository and use that for each file we stage. This would of course make it much less safe since we transfer the encryption key as part of the metadata on a Sync. People we sync with could then open all of our files, with the current schema it would be only certain files. At the cost of any de-duplication at we could also generate random keys.

If we change the encryption scheme we could also get the size and content-hash as by-product of ``ipfs add``. But I need some more time to think about a good one here.
This might also help making FUSE more reliable.

...did we mention something about a rabbithole? :smirk:

> Do we have any encryption throughput benchmarks?

Well, not really. We have [this](https://github.com/sahib/brig/blob/9f2e5a94c163eb67e5acc74540a11ceeaaed8f9b/catfs/mio/encrypt/format_test.go#L168) and I did some as part of my thesis, but those were very superficial due to time constraints.  They might be out-dated anyways and comparing number with your won't work due to different machine. Time to re-do them properly. :smile: But don't expect that encryption itself will get a lot faster.

**Comment by evgmik** [comment]
Ok. We are focusing on bug ironing for 0.6.0, I will try to be focused on it.

By the way you there are benchmark in the original thesis
https://disorganizer.github.io/brig-thesis/brig/html/index.html
in the section [8.4.2 Ergebnisse] and Figures 46-49. Unfortunately, it is not exactly clear what  and how it was benchmarked, and the color choice is very unfortunate.

As for this issue, we cannot fix it with a current design without a major rework. We need a seekable stream and the easiest way to get it is to seek in the file or
some sort of cache but a file is a cache in this sense. So I guess we closing the issue for now.

**Comment by sahib** [comment]
> By the way you there are benchmark in the original thesis

Yep, they're not very good. 

> As for this issue, we cannot fix it with a current design without a major rework. We need a seekable stream and the easiest way to get it is to seek in the file or some sort of cache but a file is a cache in this sense. So I guess we closing the issue for now.

Yes, the original issue was done. But I will open new issues from this discussion:

* Change the encryption stream to lax the requirement of seekable streams (#66). 
* I would like to see proper implementation of ``brig stage --stdin`` over Cap'n Proto streaming. That's the only portable way, we can optimize later with UDS if the next ticket asks for it (#67).
* Doing automated benchmarks for the throughputs I mentioned - we're gonna need those sooner or later anyways. (#68)
